version: "3.7"

services: 
  database_microcms:
    image: mongo
    container_name: database_microcms
    restart: always
    ports: 
      - 27017:27017
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
      - mongodb-data:/data/db
    networks:
      - mongodb-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=database_microcms
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    volumes:
      - mongodb-data:/data/mongo-express
    depends_on: 
      - database_microcms
    networks: 
      - mongodb-network
    ports:
      - 8081:8081
    restart: always
  app:
    build: .
    container_name: microcms
    networks:
      - mongodb-network
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb-network:
    name: mongodb-network

